package com.weipai.mapper;

import com.weipai.model.ExchangeLot;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface ExchangeLotMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_lot
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_lot
     *
     * @mbggenerated
     */
    int insert(ExchangeLot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_lot
     *
     * @mbggenerated
     */
    int insertSelective(ExchangeLot record);
    
    int updateSelective(Map<String,Object> map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_lot
     *
     * @mbggenerated
     */
    List<ExchangeLot> getRecentExchangeLot(Map<String,Object> map);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_lot
     *
     * @mbggenerated
     */
    ExchangeLot selectByPrimaryKey(Integer id);
    
    ExchangeLot selectExchangeByRandomNum(String randomNum);

   
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_lot
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ExchangeLot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_lot
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ExchangeLot record);
}