package com.weipai.mapper;

import com.weipai.model.PaylogLot;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PaylogLotMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paylog_lot
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paylog_lot
     *
     * @mbggenerated
     */
    int insert(PaylogLot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paylog_lot
     *
     * @mbggenerated
     */
    int insertSelective(PaylogLot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paylog_lot
     *
     * @mbggenerated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paylog_lot
     *
     * @mbggenerated
     */
    PaylogLot selectByPrimaryKey(Integer id);

  
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paylog_lot
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PaylogLot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paylog_lot
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PaylogLot record);
}