package com.weipai.model;

import java.util.Date;

public class BetlogLot {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column betlog_lot.id
     *
     * @mbggenerated
     */
    private Integer id;
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column betlog_lot.uuid
     *
     * @mbggenerated
     */
    private Integer uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column betlog_lot.serialNum
     *
     * @mbggenerated
     */
    private Long serialnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column betlog_lot.lotId
     *
     * @mbggenerated
     */
    private Integer lotid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column betlog_lot.betType
     *
     * @mbggenerated
     */
    private Integer bettype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column betlog_lot.betMount
     *
     * @mbggenerated
     */
    private Integer betmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column betlog_lot.betResult
     *
     * @mbggenerated
     */
    private Integer betresult;

    private Date createtime;
    private String lotResult;
    private String facevalue;
    private String cardcount;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column betlog_lot.id
     *
     * @return the value of betlog_lot.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column betlog_lot.id
     *
     * @param id the value for betlog_lot.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column betlog_lot.uuid
     *
     * @return the value of betlog_lot.uuid
     *
     * @mbggenerated
     */
    public Integer getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column betlog_lot.uuid
     *
     * @param uuid the value for betlog_lot.uuid
     *
     * @mbggenerated
     */
    public void setUuid(Integer uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column betlog_lot.serialNum
     *
     * @return the value of betlog_lot.serialNum
     *
     * @mbggenerated
     */
    public Long getSerialnum() {
        return serialnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column betlog_lot.serialNum
     *
     * @param serialnum the value for betlog_lot.serialNum
     *
     * @mbggenerated
     */
    public void setSerialnum(Long serialnum) {
        this.serialnum = serialnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column betlog_lot.lotId
     *
     * @return the value of betlog_lot.lotId
     *
     * @mbggenerated
     */
    public Integer getLotid() {
        return lotid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column betlog_lot.lotId
     *
     * @param lotid the value for betlog_lot.lotId
     *
     * @mbggenerated
     */
    public void setLotid(Integer lotid) {
        this.lotid = lotid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column betlog_lot.betType
     *
     * @return the value of betlog_lot.betType
     *
     * @mbggenerated
     */
    public Integer getBettype() {
        return bettype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column betlog_lot.betType
     *
     * @param bettype the value for betlog_lot.betType
     *
     * @mbggenerated
     */
    public void setBettype(Integer bettype) {
        this.bettype = bettype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column betlog_lot.betMount
     *
     * @return the value of betlog_lot.betMount
     *
     * @mbggenerated
     */
    public Integer getBetmount() {
        return betmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column betlog_lot.betMount
     *
     * @param betmount the value for betlog_lot.betMount
     *
     * @mbggenerated
     */
    public void setBetmount(Integer betmount) {
        this.betmount = betmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column betlog_lot.betResult
     *
     * @return the value of betlog_lot.betResult
     *
     * @mbggenerated
     */
    public Integer getBetresult() {
        return betresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column betlog_lot.betResult
     *
     * @param betresult the value for betlog_lot.betResult
     *
     * @mbggenerated
     */
    public void setBetresult(Integer betresult) {
        this.betresult = betresult;
    }

	public Date getCreatetime() {
		return createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public String getLotResult() {
		return lotResult;
	}

	public void setLotResult(String lotResult) {
		this.lotResult = lotResult;
	}

	public String getFacevalue() {
		return facevalue;
	}

	public void setFacevalue(String facevalue) {
		this.facevalue = facevalue;
	}

	public String getCardcount() {
		return cardcount;
	}

	public void setCardcount(String cardcount) {
		this.cardcount = cardcount;
	}

	public String getNickName() {
		return nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	
    
}